const StackList = [
  {
    name: "HTML",
    img: `${process.env.PUBLIC_URL}/img/stacks/html_icon.svg`,
    title: "웹 표준과 웹 접근성을 중시하는 HTML 정보 구조설계",
    desc: [
      "HTML 권장 마크업 방식 및 시멘틱 태그의 사용",
      "기획서의 제작을 통한 체계적인 퍼블리싱",
      "class와 id 등을 통한 꼼꼼한 HTML 정보 구조설계",
    ],
    color: "#f1662a",
    font: "#ffffff",
    border: "f1662a",
  },
  {
    name: "CSS",
    img: `${process.env.PUBLIC_URL}/img/stacks/css_icon.svg`,
    title: "IE까지 염두에 둔 크로스 브라우징을 위한 CSS 코딩",
    desc: [
      "안정적인 CSS 속성의 사용 및 배치, 디자인",
      "필요 여하에 따른 CSS3 지원 속성의 활용",
      "Flex와 Gird 및 position 속성, Media Query를 활용한 반응형 웹 제작",
    ],
    color: "#33A9DC",
    font: "#FFFFFF",
    border: "33A9DC",
  },
  {
    name: "JS",
    img: `${process.env.PUBLIC_URL}/img/stacks/js_icon.svg`,
    title: "재사용성과 확장성이 높은 코드",
    desc: [
      "Selector와 EventListener를 사용한 이벤트의 구현",
      "조건문, 반복문 등의 활용으로 생산성과 효율성이 높은 코드 작성",
      "API 및 Swiper 등의 플러그인 활용",
    ],
    color: "#F7DF1E",
    font: "#020715",
    border: "#020715",
  },
  {
    name: "jQuery",
    img: `${process.env.PUBLIC_URL}/img/stacks/jquery_icon.svg`,
    title: "플러그인을 사용하지 않는 순수한 jQuery 코딩",
    desc: [
      "각종 이벤트의 처리 및 jQuery만의 명령어 사용",
      "필요 여하에 따른 jQuery Plugin의 사용 및 커스터마이징",
      "빠른 개발과 높은 생산성의 필요한 경우에 활용",
    ],
    color: "#ffffff",
    font: "#0868AC",
    border: "#0868AC",
  },
  {
    name: "React",
    img: `${process.env.PUBLIC_URL}/img/stacks/react_icon.svg`,
    title: "CSR의 장점은 살리고 단점은 최소화하는 코딩",
    desc: [
      "",
      "Router의 사용으로 SPA와 CSR의 장점인 부드러운 화면 전환을 활용",
      "로딩 애니메이션의 활용으로 사용자의 이탈을 최소화",
      "Styled-Components를 통한 코드 경량화, CSS 유지보수 부담의 감소",
    ],
    color: "#282c34",
    font: "#00D8FF",
    border: "#00D8FF",
  },
  {
    name: "SASS",
    img: `${process.env.PUBLIC_URL}/img/stacks/sass_icon.svg`,
    title: "SASS를 통한 CSS의 단점 보완",
    desc: [
      "기존 CSS의 복잡성을 줄여, 유지보수에 유리",
      "$ 변수 문법을 통한 높은 생산성 확보",
      "반복문과 조건문을 통한 코드 간소화",
    ],
    color: "#ffffff",
    font: "#CD6799",
    border: "#CD6799",
  },
  {
    name: "BootStrap",
    img: `${process.env.PUBLIC_URL}/img/stacks/bs_icon.svg`,
    title: "BootStrap을 사용한 빠른 개발 및 커스터마이징",
    desc: [
      "빠른 개발과 높은 효율에 따른 사용",
      "BootStrap을 사용한 모달 및 기타 컴포넌트들의 커스터마이징",
      "단순 BootStrap 만이 아닌 React-BootStrap 역시 활용",
    ],
    color: "#ffffff",
    font: "#7E13F8",
    border: "#7E13F8",
  },
  {
    name: "VSCODE",
    img: `${process.env.PUBLIC_URL}/img/stacks/vs_icon.svg`,
    title: "추가 기능과 스니펫을 활용한 텍스트 에디터의 활용",
    desc: [
      "각종 플러그인을 통한 생산성 증대",
      "스니펫과 json 파일의 수정을 통한 효율성 증대",
      "각종 단축키의 커스터마이징",
    ],
    color: "#ffffff",
    font: "#1F9CF0",
    border: "#1F9CF0",
  },
  {
    name: "Git",
    img: `${process.env.PUBLIC_URL}/img/stacks/git_icon.svg`,
    title: "버전 및 형상관리를 위한 Git 사용",
    desc: [
      "작업물에 대한 commit 및 자동 commit의 사용으로 확실한 버전 관리",
      "merge와 pull request를 통한 협업",
      "Branch를 활용한 기능 개발의 안정성 확보",
    ],
    color: "#ffffff",
    font: "#F34F29",
    border: "#F34F29",
  },
  {
    name: "Github",
    img: `${process.env.PUBLIC_URL}/img/stacks/github_icon.svg`,
    title: "",
    desc: [
      "git clone과 pull request를 활용한 협업",
      "리모트 리포지토리의 관리 및 Branch 간의 Merge",
      "여러 종류의 Merge 및 Merge로 인한 Conflict의 해결",
    ],
    color: "#ffffff",
    font: "#000000",
    border: "#000000",
  },
  {
    name: "Figma",
    img: `${process.env.PUBLIC_URL}/img/stacks/figma_icon.svg`,
    title: "와이어프레임과 시안을 위한 초석",
    desc: [
      "피그잼을 통한 브레인스토밍 및 계획의 수립",
      "피그마 파일을 통한 와이어프레임 디자인 및 시안 계획",
      "Prototype 탭의 기능을 통한 Hover 액션 및 Frame 이동의 구현",
    ],
    color: "#ffffff",
    font: "#A259FF",
    border: "#A259FF",
  },
  {
    name: "Slack",
    img: `${process.env.PUBLIC_URL}/img/stacks/slack_icon.svg`,
    title: "팀원들과의 의사소통",
    desc: [
      "단순 회의만이 아닌 각종 공유 및 피드백으로의 사용",
      "코드 공유 및 화면 공유를 통한 생산성 증대",
      "메뉴 분할, 노션 및 피그마의 혼용을 통한 팀원과의 회의 기록 및 계획 수립",
    ],
    color: "#ffffff",
    font: "#2EB57D",
    border: "#2EB57D",
  },
  {
    name: "PhotoShop",
    img: `${process.env.PUBLIC_URL}/img/stacks/ps_icon.svg`,
    title: "PhotoShop을 활용한 배경 처리 및 이미지 수정",
    desc: [
      "이미지 외곽선 등의 처리를 통한 이미지 가시성 증가",
      "PS 툴을 사용한 배경이미지의 확장 처리",
      "배경 제거를 통한 이미지 활용성 증대",
    ],
    color: "#001E36",
    font: "#31A8FF",
    border: "#31A8FF",
  },
  {
    name: "Illustrator",
    img: `${process.env.PUBLIC_URL}/img/stacks/ai_icon.svg`,
    title: "SVG 파일의 관리를 위한 일러스트레이터",
    desc: [
      "stroke, fill 속성 등의 관리",
      "SVG 파일의 group 등의 간단한 수정 및 처리",
      "CMYK와 RGB의 차이를 염두에 둔 이미지 처리",
    ],
    color: "#330000",
    font: "#FF9A00",
    border: "#FF9A00",
  },
  {
    name: "Notion",
    img: `${process.env.PUBLIC_URL}/img/stacks/notion_icon.svg`,
    title: "협업 및 기획을 위한 Notion의 사용",
    desc: [
      "협업 페이지의 개설을 통한 협업 생산성 증대",
      "각종 사용 기술 및 협업에 따른 룰 부여로 취합 등에 따른 리스크 감소",
      "타임라인 및 게시판 등의 활용을 통해 파트 분담 및 작업 촉진",
    ],
    color: "#ffffff",
    font: "#000000",
    border: "#000000",
  },
];
export default StackList;
